lab:
  Mono:
    black:
      max:
      - 132
      - 255
      - 132
      min:
      - 0
      - 116
      - 0
    blue:
      max:
      - 255
      - 255
      - 101
      min:
      - 0
      - 0
      - 0
    green:
      max:
      - 255
      - 255
      - 255
      min:
      - 0
      - 0
      - 172
    red:
      max:
      - 255
      - 255
      - 255
      min:
      - 0
      - 155
      - 119
    white:
      max:
      - 255
      - 255
      - 255
      min:
      - 193
      - 0
      - 0
    yellow:
      max:
      - 255
      - 255
      - 255
      min:
      - 160
      - 102
      - 144
    zise:
      max:
      - 226
      - 209
      - 133
      min:
      - 77
      - 150
      - 34
    zz:
      max:
      - 255
      - 255
      - 255
      min:
      - 0
      - 0
      - 0
  Stereo:
    black:
      max:
      - 123
      - 255
      - 255
      min:
      - 0
      - 0
      - 0
    blue:
      max:
      - 255
      - 143
      - 105
      min:
      - 0
      - 0
      - 0
    green:
      max:
      - 255
      - 110
      - 255
      min:
      - 47
      - 0
      - 135
    red:
      max:
      - 255
      - 255
      - 255
      min:
      - 0
      - 150
      - 144
    white:
      max:
      - 255
      - 255
      - 255
      min:
      - 193
      - 0
      - 0
    yellow:
      max:
      - 255
      - 255
      - 255
      min:
      - 117
      - 120
      - 130
size:
  height:
  - 480
  width:
  - 640
